In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.utils import shuffle
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import log_loss
from sklearn.ensemble import RandomForestClassifier

from datetime import datetime

In [2]:
# Load the data sets
data_dir = './data/'
df_Household = pd.read_csv(data_dir + 'Household.csv')
df_Trip = pd.read_csv(data_dir + 'Trip.csv')
df_Person = pd.read_csv(data_dir + 'Person.csv')
df_Blockgroup_UrbanVillage = pd.read_csv(data_dir + 'Blockgroup_UrbanVillage.csv')

#print (df_Household.head())
print (df_Blockgroup_UrbanVillage.head())

/Users/xx/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (6,18,21,24,25,26,28,29,31,33,90,112) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

     BLOCKGROUP URBAN_VILLAGE_NAME URBAN_VILLAGE_TYPE  \
0  530330001001   Outside Villages   Outside Villages
1  530330001002   Outside Villages   Outside Villages
2  530330001003   Outside Villages   Outside Villages
3  530330001004   Outside Villages   Outside Villages
4  530330001005   Outside Villages   Outside Villages

                              NEIGHBORHOODS_INCLUDED  \
0  Cedar Park, Lake City, Meadowbrook, Matthews B...
1  Cedar Park, Lake City, Meadowbrook, Matthews B...
2  Cedar Park, Lake City, Meadowbrook, Matthews B...
3  Cedar Park, Lake City, Meadowbrook, Matthews B...
4  Cedar Park, Lake City, Meadowbrook, Matthews B...

   NEIGHBORHOOD_DISTRICT_NUMBER NEIGHBORHOOD_DISTRICT_NAME
0                             8                      North
1                             8                      North
2                             8                      North
3                             8                      North
4                             8                      North

## Process Persons (Race demographics)

In [3]:
# load race information
df_persons = df_Person[['hhid','race_afam','race_aiak','race_asian','race_hapi','race_hisp','race_white','race_other']]
df_persons.dropna(axis = 0, inplace=True)

#race_afam	race_aiak	race_asian	race_hapi	race_hisp	race_white	race_other

df_race = df_persons.groupby(['hhid'], as_index=False).agg({'race_afam':sum,'race_aiak':sum,
                                                        'race_asian':sum,'race_hapi':sum,
                                                            'race_white':sum,'race_other':sum,
                                                           'race_hisp':sum})

df_race['race_total'] = df_race['race_afam'] + df_race['race_asian'] + df_race['race_hisp'] + df_race['race_white'] + df_race['race_other']
df_race['pct_white'] = df_race['race_white'] / df_race['race_total']
print (df_race)

          hhid  race_afam  race_aiak  race_asian  race_hapi  race_white  \
0     17100005        0.0        0.0         0.0        0.0         2.0
1     17100024        0.0        0.0         0.0        0.0         2.0
2     17100052        0.0        0.0         0.0        0.0         1.0
3     17100059        0.0        0.0         0.0        0.0         0.0
4     17100060        0.0        0.0         0.0        0.0         1.0
5     17100102        0.0        0.0         1.0        0.0         1.0
6     17100108        0.0        0.0         0.0        0.0         0.0
7     17100111        0.0        0.0         1.0        0.0         2.0
8     17100137        0.0        0.0         0.0        0.0         1.0
9     17100149        0.0        0.0         2.0        0.0         0.0
10    17100179        0.0        0.0         0.0        0.0         2.0
11    17100203        0.0        0.0         2.0        0.0         0.0
12    17100208        0.0        0.0         0.0        0.0         1.0
13    17100221        0.0        0.0         1.0        0.0         1.0
14    17100231        0.0        0.0         0.0        0.0         2.0
15    17100233        0.0        0.0         0.0        0.0         0.0
16    17100238        0.0        0.0         0.0        0.0         2.0
17    17100248        0.0        0.0         0.0        0.0         1.0
18    17100255        0.0        0.0         0.0        0.0         1.0
19    17100280        0.0        0.0         0.0        0.0         1.0
20    17100291        1.0        0.0         2.0        0.0         2.0
21    17100303        1.0        0.0         2.0        1.0         1.0
22    17100326        0.0        0.0         0.0        0.0         2.0
23    17100342        0.0        0.0         0.0        0.0         2.0
24    17100372        0.0        0.0         0.0        0.0         2.0
25    17100410        0.0        0.0         0.0        0.0         1.0
26    17100411        0.0        1.0         0.0        0.0         1.0
27    17100414        0.0        0.0         0.0        0.0         2.0
28    17100418        0.0        0.0         0.0        0.0         2.0
29    17100433        0.0        0.0         2.0        0.0         0.0
...        ...        ...        ...         ...        ...         ...
3255  17153587        0.0        0.0         0.0        0.0         2.0
3256  17153608        0.0        0.0         0.0        0.0         1.0
3257  17153614        0.0        0.0         0.0        0.0         2.0
3258  17153632        0.0        0.0         0.0        0.0         0.0
3259  17153681        0.0        0.0         0.0        0.0         2.0
3260  17153688        0.0        0.0         0.0        0.0         1.0
3261  17153690        0.0        0.0         0.0        0.0         2.0
3262  17153702        0.0        0.0         0.0        0.0         2.0
3263  17153716        0.0        0.0         0.0        0.0         1.0
3264  17153725        0.0        0.0         0.0        0.0         1.0
3265  17153730        0.0        0.0         0.0        1.0         1.0
3266  17153749        0.0        0.0         0.0        0.0         2.0
3267  17153751        0.0        0.0         0.0        0.0         1.0
3268  17153788        0.0        0.0         0.0        0.0         1.0
3269  17153829        0.0        0.0         0.0        0.0         2.0
3270  17153832        0.0        0.0         0.0        0.0         0.0
3271  17153834        0.0        0.0         0.0        0.0         0.0
3272  17153852        0.0        0.0         0.0        0.0         1.0
3273  17153860        0.0        0.0         1.0        0.0         1.0
3274  17153865        0.0        0.0         0.0        0.0         1.0
3275  17153913        0.0        0.0         0.0        0.0         1.0
3276  17153932        0.0        0.0         0.0        0.0         1.0
3277  17153959        0.0        0.0         0.0        0.0         2.0
3278  17153978        0.0        0.0         0.0        0.0         3.0
3279  17154020        0.0        0.0         1.0        0.0         0.0
3280  17154101        0.0        0.0         0.0        0.0         0.0
3281  17154108        0.0        0.0         1.0        0.0         0.0
3282  17154129        0.0        0.0         0.0        0.0         2.0
3283  17154152        0.0        0.0         2.0        0.0         0.0
3284  17154199        0.0        0.0         1.0        0.0         1.0

      race_other  race_hisp  race_total  pct_white
0            0.0        0.0         2.0   1.000000
1            0.0        0.0         2.0   1.000000
2            0.0        0.0         1.0   1.000000
3            1.0        0.0         1.0   0.000000
4            0.0        0.0         1.0   1.000000
5            0.0        0.0         2.0   0.500000
6            0.0        0.0         0.0        NaN
7            0.0        0.0         3.0   0.666667
8            0.0        0.0         1.0   1.000000
9            0.0        0.0         2.0   0.000000
10           0.0        0.0         2.0   1.000000
11           0.0        0.0         2.0   0.000000
12           1.0        1.0         3.0   0.333333
13           1.0        0.0         3.0   0.333333
14           0.0        0.0         2.0   1.000000
15           0.0        0.0         0.0        NaN
16           0.0        0.0         2.0   1.000000
17           0.0        0.0         1.0   1.000000
18           0.0        0.0         1.0   1.000000
19           0.0        0.0         1.0   1.000000
20           0.0        0.0         5.0   0.400000
21           0.0        0.0         4.0   0.250000
22           0.0        0.0         2.0   1.000000
23           0.0        0.0         2.0   1.000000
24           0.0        0.0         2.0   1.000000
25           0.0        1.0         2.0   0.500000
26           0.0        0.0         1.0   1.000000
27           0.0        0.0         2.0   1.000000
28           0.0        0.0         2.0   1.000000
29           0.0        0.0         2.0   0.000000
...          ...        ...         ...        ...
3255         0.0        0.0         2.0   1.000000
3256         0.0        0.0         1.0   1.000000
3257         0.0        0.0         2.0   1.000000
3258         0.0        0.0         0.0        NaN
3259         0.0        0.0         2.0   1.000000
3260         0.0        0.0         1.0   1.000000
3261         0.0        0.0         2.0   1.000000
3262         0.0        0.0         2.0   1.000000
3263         0.0        0.0         1.0   1.000000
3264         0.0        0.0         1.0   1.000000
3265         0.0        0.0         1.0   1.000000
3266         0.0        0.0         2.0   1.000000
3267         0.0        0.0         1.0   1.000000
3268         0.0        0.0         1.0   1.000000
3269         0.0        0.0         2.0   1.000000
3270         0.0        0.0         0.0        NaN
3271         0.0        0.0         0.0        NaN
3272         0.0        0.0         1.0   1.000000
3273         0.0        0.0         2.0   0.500000
3274         0.0        0.0         1.0   1.000000
3275         0.0        0.0         1.0   1.000000
3276         0.0        0.0         1.0   1.000000
3277         0.0        0.0         2.0   1.000000
3278         0.0        0.0         3.0   1.000000
3279         0.0        0.0         1.0   0.000000
3280         0.0        0.0         0.0        NaN
3281         0.0        0.0         1.0   0.000000
3282         0.0        0.0         2.0   1.000000
3283         0.0        0.0         2.0   0.000000
3284         0.0        0.0         2.0   0.500000

[3285 rows x 10 columns]

/Users/xx/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

## Process Households

In [4]:
# load household data
df_households = df_Household[['bg_household','hhid','final_lat','final_lng','hhsize','vehicle_count','numchildren',
                 'hhincome_broad','car_share','rent_own','res_dur','offpark','hh_wt_final']]

df_households['bg_household'] = df_households['bg_household'].astype(float).astype(int).astype(str)
# merge with seattle block group data
df_seattle = df_Blockgroup_UrbanVillage[['BLOCKGROUP','URBAN_VILLAGE_NAME','URBAN_VILLAGE_TYPE']]
df_seattle['bg_household'] = df_seattle['BLOCKGROUP'].astype(str)

df_households = pd.merge(left=df_households, right=df_seattle, how='left', on='bg_household')
df_households.drop(['BLOCKGROUP'], axis = 1, inplace=True)
df_households['URBAN_VILLAGE_NAME'] = df_households['URBAN_VILLAGE_NAME'].fillna("Outside Seattle")
df_households['URBAN_VILLAGE_TYPE'] = df_households['URBAN_VILLAGE_TYPE'].fillna("Outside Seattle")

df_households = df_households.rename(columns={'final_lat':'hh_lat', 'final_lng':'hh_lng'})
df_households = df_households.rename(columns={'URBAN_VILLAGE_NAME':'hh_uv', 'URBAN_VILLAGE_TYPE':'hh_uv_type'})

# Assign income variables
df_households['income'] = np.where(df_households['hhincome_broad']==1, "Under $25,000", "")
df_households['income'] = np.where(df_households['hhincome_broad']==2, "$25,000-$49,999", df_households['income'])
df_households['income'] = np.where(df_households['hhincome_broad']==3, "$50,000-$74,999", df_households['income'])
df_households['income'] = np.where(df_households['hhincome_broad']==4, "$75,000-$99,999", df_households['income'])
df_households['income'] = np.where(df_households['hhincome_broad']==5, "$100,000 or more", df_households['income'])
df_households['income'] = np.where(df_households['hhincome_broad']==6, "Prefer not to answer", df_households['income'])

# Assign home ownership
df_households['homeownership'] = np.where(df_households['rent_own']==1, "Own", "Other")
df_households['homeownership'] = np.where(df_households['rent_own']==2, "Rent", df_households['homeownership'])

# Assign residency tenure
df_households['tenure'] = np.where(df_households['res_dur']==1, "Less than a year", "")
df_households['tenure'] = np.where(df_households['res_dur']==2, "Between 1 and 2 years", df_households['tenure'])
df_households['tenure'] = np.where(df_households['res_dur']==3, "Between 2 and 3 years", df_households['tenure'])
df_households['tenure'] = np.where(df_households['res_dur']==4, "Between 3 and 5 years", df_households['tenure'])
df_households['tenure'] = np.where(df_households['res_dur']==5, "Between 5 and 10 years", df_households['tenure'])
df_households['tenure'] = np.where(df_households['res_dur']==6, "Between 10 and 20 years", df_households['tenure'])
df_households['tenure'] = np.where(df_households['res_dur']==7, "More than 20 years", df_households['tenure'])

df_households = pd.merge(left=df_households, right=df_race, how='left', on='hhid')

print (df_households.head())
print (df_households)

/Users/xx/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/xx/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

   bg_household      hhid     hh_lat      hh_lng  hhsize  vehicle_count  \
0  530330323234  17100005  47.695195 -122.099114       2              2
1  530330076002  17100024  47.619659 -122.304511       3              1
2  530330075005  17100052  47.620380 -122.318625       1              0
3  530330084001  17100059  47.614840 -122.324427       1              0
4  530530720002  17100060  47.120867 -122.527610       1              1

   numchildren  hhincome_broad  car_share  rent_own    ...      \
0            0               4          2         1    ...
1            1               4          1         1    ...
2            0               1          2         2    ...
3            0               5          2         2    ...
4            0               1          2         2    ...

                    tenure  race_afam  race_aiak race_asian race_hapi  \
0       More than 20 years        0.0        0.0        0.0       0.0
1    Between 1 and 2 years        0.0        0.0        0.0       0.0
2  Between 10 and 20 years        0.0        0.0        0.0       0.0
3         Less than a year        0.0        0.0        0.0       0.0
4   Between 5 and 10 years        0.0        0.0        0.0       0.0

  race_white race_other race_hisp  race_total  pct_white
0        2.0        0.0       0.0         2.0        1.0
1        2.0        0.0       0.0         2.0        1.0
2        1.0        0.0       0.0         1.0        1.0
3        0.0        1.0       0.0         1.0        0.0
4        1.0        0.0       0.0         1.0        1.0

[5 rows x 27 columns]
      bg_household      hhid     hh_lat      hh_lng  hhsize  vehicle_count  \
0     530330323234  17100005  47.695195 -122.099114       2              2
1     530330076002  17100024  47.619659 -122.304511       3              1
2     530330075005  17100052  47.620380 -122.318625       1              0
3     530330084001  17100059  47.614840 -122.324427       1              0
4     530530720002  17100060  47.120867 -122.527610       1              1
5     530330075004  17100102  47.616313 -122.317273       1              1
6     530330080022  17100108  47.612460 -122.348363       2              1
7     530330026003  17100111  47.678207 -122.310166       4              3
8     530330084002  17100137  47.612473 -122.322960       1              1
9     530330248003  17100149  47.574953 -122.170802       4              2
10    530330054003  17100179  47.649697 -122.338356       3              2
11    530330323092  17100203  47.673905 -122.114455       4              2
12    530330100024  17100208  47.572386 -122.304220       3              2
13    530330072001  17100221  47.614257 -122.343526       1              0
14    530330323232  17100231  47.696419 -122.105267       2              2
15    530330312043  17100233  47.294014 -122.134133       2              3
16    530350909001  17100238  47.624879 -122.521001       2              2
17    530330074014  17100248  47.621272 -122.324939       1              0
18    530330323092  17100255  47.677070 -122.127472       1              1
19    530330070005  17100280  47.626159 -122.358827       1              0
20    530530719011  17100291  47.171765 -122.518458       2              1
21    530330012005  17100303  47.705282 -122.333375       2              2
22    530330058023  17100326  47.636075 -122.387638       2              1
23    530330007001  17100342  47.717666 -122.294853       2              2
24    530330075002  17100372  47.615902 -122.313262       2              1
25    530330075004  17100410  47.613612 -122.313162       1              0
26    530330053011  17100411  47.664143 -122.306868       1              0
27    530330099002  17100414  47.564935 -122.357627       3              2
28    530330323091  17100418  47.672843 -122.129513       2              2
29    530330323243  17100433  47.680801 -122.121855       2              1
...            ...       ...        ...         ...     ...            ...
3255  530330093001  17153587  47.589523 -122.318601       2              2
3256  530330105004  17153608  47.561521 -122.385852       1              0
3257  530330098004  17153614  47.567157 -122.386378       2              2
3258  530530724063  17153632  47.299541 -122.620685       2              2
3259  530330018001  17153681  47.697095 -122.341125       2              2
3260  530330087003  17153688  47.603700 -122.307066       1              2
3261  530330323252  17153690  47.688755 -122.101724       2              4
3262  530350910003  17153702  47.612827 -122.505311       2              2
3263  530330074011  17153716  47.623963 -122.323704       1              0
3264  530330323092  17153725  47.676277 -122.121228       1              1
3265  530330012003  17153730  47.708590 -122.323235       4              1
3266  530330323242  17153749  47.676282 -122.110958       4              2
3267  530330106003  17153751  47.542113 -122.389590       1              1
3268  530330323092  17153788  47.673905 -122.114455       1              1
3269  530330074013  17153829  47.622557 -122.326979       2              1
3270  530330073003  17153832  47.614577 -122.337189       1              0
3271  530330323134  17153834  47.660067 -122.090452       4              1
3272  530330047004  17153852  47.671889 -122.384495       1              0
3273  530330074021  17153860  47.619679 -122.322536       1              1
3274  530330211003  17153865  47.737138 -122.304978       2              2
3275  530330047004  17153913  47.671140 -122.384271       1              1
3276  530330007001  17153932  47.718416 -122.297369       1              1
3277  530330316053  17153959  47.342558 -122.037046       2              4
3278  530330323271  17153978  47.699335 -122.040669       4              3
3279  530330044004  17154020  47.668364 -122.312741       2              0
3280  530330076001  17154101  47.624189 -122.311782       2              2
3281  530330043021  17154108  47.663911 -122.306187       1              0
3282  530330110013  17154129  47.534593 -122.286387       2              1
3283  530330095001  17154152  47.583237 -122.292342       3              2
3284  530530719011  17154199  47.171765 -122.518458       2              1

      numchildren  hhincome_broad  car_share  rent_own    ...      \
0               0               4          2         1    ...
1               1               4          1         1    ...
2               0               1          2         2    ...
3               0               5          2         2    ...
4               0               1          2         2    ...
5               0               4          2         2    ...
6               0               5          1         2    ...
7               2               5          2         1    ...
8               0               1          2         1    ...
9               2               5          1         1    ...
10              1               5          2         1    ...
11              2               5          2         2    ...
12              1               3          2         2    ...
13              0               5          2         2    ...
14              0               6          2         4    ...
15              0               5          2         1    ...
16              0               5          2         1    ...
17              0               5          1         1    ...
18              0               5          2         2    ...
19              0               2          1         2    ...
20              0               2          2         2    ...
21              0               3          1         2    ...
22              0               5          2         2    ...
23              0               5          2         2    ...
24              0               5          1         2    ...
25              0               3          1         2    ...
26              0               3          2         2    ...
27              1               5          2         1    ...
28              0               5          2         2    ...
29              0               2          2         2    ...
...           ...             ...        ...       ...    ...
3255            0               5          2         1    ...
3256            0               1          2         2    ...
3257            0               4          1         2    ...
3258            0               3          2         1    ...
3259            0               5          2         2    ...
3260            0               4          2         1    ...
3261            0               5          2         1    ...
3262            0               4          2         2    ...
3263            0               2          2         2    ...
3264            0               5          2         2    ...
3265            2               4          2         2    ...
3266            2               5          2         2    ...
3267            0               5          2         1    ...
3268            0               5          2         2    ...
3269            0               3          2         2    ...
3270            0               5          1         2    ...
3271            2               4          2         2    ...
3272            0               3          2         2    ...
3273            0               1          1         2    ...
3274            1               2          2         1    ...
3275            0               3          2         2    ...
3276            0               4          2         2    ...
3277            0               5          2         1    ...
3278            1               5          2         1    ...
3279            0               2          2         2    ...
3280            0               5          1         2    ...
3281            0               2          2         2    ...
3282            0               4          2         1    ...
3283            1               5          2         1    ...
3284            0               2          2         2    ...

                       tenure  race_afam  race_aiak race_asian race_hapi  \
0          More than 20 years        0.0        0.0        0.0       0.0
1       Between 1 and 2 years        0.0        0.0        0.0       0.0
2     Between 10 and 20 years        0.0        0.0        0.0       0.0
3            Less than a year        0.0        0.0        0.0       0.0
4      Between 5 and 10 years        0.0        0.0        0.0       0.0
5       Between 3 and 5 years        0.0        0.0        1.0       0.0
6       Between 1 and 2 years        0.0        0.0        0.0       0.0
7          More than 20 years        0.0        0.0        1.0       0.0
8       Between 3 and 5 years        0.0        0.0        0.0       0.0
9       Between 2 and 3 years        0.0        0.0        2.0       0.0
10         More than 20 years        0.0        0.0        0.0       0.0
11      Between 3 and 5 years        0.0        0.0        2.0       0.0
12      Between 2 and 3 years        0.0        0.0        0.0       0.0
13           Less than a year        0.0        0.0        1.0       0.0
14      Between 2 and 3 years        0.0        0.0        0.0       0.0
15         More than 20 years        0.0        0.0        0.0       0.0
16    Between 10 and 20 years        0.0        0.0        0.0       0.0
17      Between 3 and 5 years        0.0        0.0        0.0       0.0
18           Less than a year        0.0        0.0        0.0       0.0
19     Between 5 and 10 years        0.0        0.0        0.0       0.0
20    Between 10 and 20 years        1.0        0.0        2.0       0.0
21      Between 1 and 2 years        1.0        0.0        2.0       1.0
22      Between 1 and 2 years        0.0        0.0        0.0       0.0
23           Less than a year        0.0        0.0        0.0       0.0
24     Between 5 and 10 years        0.0        0.0        0.0       0.0
25      Between 3 and 5 years        0.0        0.0        0.0       0.0
26     Between 5 and 10 years        0.0        1.0        0.0       0.0
27      Between 2 and 3 years        0.0        0.0        0.0       0.0
28      Between 2 and 3 years        0.0        0.0        0.0       0.0
29      Between 1 and 2 years        0.0        0.0        2.0       0.0
...                       ...        ...        ...        ...       ...
3255    Between 3 and 5 years        0.0        0.0        0.0       0.0
3256  Between 10 and 20 years        0.0        0.0        0.0       0.0
3257    Between 1 and 2 years        0.0        0.0        0.0       0.0
3258  Between 10 and 20 years        0.0        0.0        0.0       0.0
3259    Between 3 and 5 years        0.0        0.0        0.0       0.0
3260  Between 10 and 20 years        0.0        0.0        0.0       0.0
3261  Between 10 and 20 years        0.0        0.0        0.0       0.0
3262         Less than a year        0.0        0.0        0.0       0.0
3263    Between 3 and 5 years        0.0        0.0        0.0       0.0
3264    Between 1 and 2 years        0.0        0.0        0.0       0.0
3265    Between 3 and 5 years        0.0        0.0        0.0       1.0
3266   Between 5 and 10 years        0.0        0.0        0.0       0.0
3267  Between 10 and 20 years        0.0        0.0        0.0       0.0
3268    Between 3 and 5 years        0.0        0.0        0.0       0.0
3269  Between 10 and 20 years        0.0        0.0        0.0       0.0
3270    Between 3 and 5 years        0.0        0.0        0.0       0.0
3271         Less than a year        0.0        0.0        0.0       0.0
3272         Less than a year        0.0        0.0        0.0       0.0
3273    Between 1 and 2 years        0.0        0.0        1.0       0.0
3274   Between 5 and 10 years        0.0        0.0        0.0       0.0
3275   Between 5 and 10 years        0.0        0.0        0.0       0.0
3276    Between 2 and 3 years        0.0        0.0        0.0       0.0
3277       More than 20 years        0.0        0.0        0.0       0.0
3278    Between 3 and 5 years        0.0        0.0        0.0       0.0
3279    Between 2 and 3 years        0.0        0.0        1.0       0.0
3280    Between 1 and 2 years        0.0        0.0        0.0       0.0
3281         Less than a year        0.0        0.0        1.0       0.0
3282    Between 1 and 2 years        0.0        0.0        0.0       0.0
3283   Between 5 and 10 years        0.0        0.0        2.0       0.0
3284         Less than a year        0.0        0.0        1.0       0.0

     race_white race_other race_hisp  race_total  pct_white
0           2.0        0.0       0.0         2.0   1.000000
1           2.0        0.0       0.0         2.0   1.000000
2           1.0        0.0       0.0         1.0   1.000000
3           0.0        1.0       0.0         1.0   0.000000
4           1.0        0.0       0.0         1.0   1.000000
5           1.0        0.0       0.0         2.0   0.500000
6           0.0        0.0       0.0         0.0        NaN
7           2.0        0.0       0.0         3.0   0.666667
8           1.0        0.0       0.0         1.0   1.000000
9           0.0        0.0       0.0         2.0   0.000000
10          2.0        0.0       0.0         2.0   1.000000
11          0.0        0.0       0.0         2.0   0.000000
12          1.0        1.0       1.0         3.0   0.333333
13          1.0        1.0       0.0         3.0   0.333333
14          2.0        0.0       0.0         2.0   1.000000
15          0.0        0.0       0.0         0.0        NaN
16          2.0        0.0       0.0         2.0   1.000000
17          1.0        0.0       0.0         1.0   1.000000
18          1.0        0.0       0.0         1.0   1.000000
19          1.0        0.0       0.0         1.0   1.000000
20          2.0        0.0       0.0         5.0   0.400000
21          1.0        0.0       0.0         4.0   0.250000
22          2.0        0.0       0.0         2.0   1.000000
23          2.0        0.0       0.0         2.0   1.000000
24          2.0        0.0       0.0         2.0   1.000000
25          1.0        0.0       1.0         2.0   0.500000
26          1.0        0.0       0.0         1.0   1.000000
27          2.0        0.0       0.0         2.0   1.000000
28          2.0        0.0       0.0         2.0   1.000000
29          0.0        0.0       0.0         2.0   0.000000
...         ...        ...       ...         ...        ...
3255        2.0        0.0       0.0         2.0   1.000000
3256        1.0        0.0       0.0         1.0   1.000000
3257        2.0        0.0       0.0         2.0   1.000000
3258        0.0        0.0       0.0         0.0        NaN
3259        2.0        0.0       0.0         2.0   1.000000
3260        1.0        0.0       0.0         1.0   1.000000
3261        2.0        0.0       0.0         2.0   1.000000
3262        2.0        0.0       0.0         2.0   1.000000
3263        1.0        0.0       0.0         1.0   1.000000
3264        1.0        0.0       0.0         1.0   1.000000
3265        1.0        0.0       0.0         1.0   1.000000
3266        2.0        0.0       0.0         2.0   1.000000
3267        1.0        0.0       0.0         1.0   1.000000
3268        1.0        0.0       0.0         1.0   1.000000
3269        2.0        0.0       0.0         2.0   1.000000
3270        0.0        0.0       0.0         0.0        NaN
3271        0.0        0.0       0.0         0.0        NaN
3272        1.0        0.0       0.0         1.0   1.000000
3273        1.0        0.0       0.0         2.0   0.500000
3274        1.0        0.0       0.0         1.0   1.000000
3275        1.0        0.0       0.0         1.0   1.000000
3276        1.0        0.0       0.0         1.0   1.000000
3277        2.0        0.0       0.0         2.0   1.000000
3278        3.0        0.0       0.0         3.0   1.000000
3279        0.0        0.0       0.0         1.0   0.000000
3280        0.0        0.0       0.0         0.0        NaN
3281        0.0        0.0       0.0         1.0   0.000000
3282        2.0        0.0       0.0         2.0   1.000000
3283        0.0        0.0       0.0         2.0   0.000000
3284        1.0        0.0       0.0         2.0   0.500000

[3285 rows x 27 columns]

## Process Trips

In [5]:
df_trips = df_Trip[['tripid','hhid','origin_lat','origin_lng','dest_lat','dest_lng',
                    'bg_origin','bg_dest','personid','google_duration','trip_path_distance',
                    'depart_time_timestamp','arrival_time_timestamp','daynum','o_purp','d_purp',
                    'mode_1','travelers_total','traveldate','trip_wt_final']]

df_trips['bg_dest'] = df_trips['bg_dest'].astype(str)
df_trips['bg_origin'] = df_trips['bg_origin'].astype(str)


# merge with seattle block group data
df_seattle = df_Blockgroup_UrbanVillage[['BLOCKGROUP','URBAN_VILLAGE_NAME','URBAN_VILLAGE_TYPE']]
df_seattle['BLOCKGROUP'] = df_seattle['BLOCKGROUP'].astype(str)
                              
df_trips = pd.merge(left=df_trips, right=df_seattle, how='left', left_on='bg_origin', right_on='BLOCKGROUP')
df_trips = df_trips.rename(columns={'URBAN_VILLAGE_NAME':'uv_origin', 'URBAN_VILLAGE_TYPE':'uvType_origin'})
df_trips.drop(['BLOCKGROUP'], axis = 1, inplace=True)

df_trips['uv_origin'] = df_trips['uv_origin'].fillna("Outside Seattle")
df_trips['uvType_origin'] = df_trips['uvType_origin'].fillna("Outside Seattle")

df_trips = pd.merge(left=df_trips, right=df_seattle, how='left', left_on='bg_dest', right_on='BLOCKGROUP')
df_trips = df_trips.rename(columns={'URBAN_VILLAGE_NAME':'uv_dest', 'URBAN_VILLAGE_TYPE':'uvType_dest'})
df_trips.drop(['BLOCKGROUP'], axis = 1, inplace=True)

df_trips['uv_dest'] = df_trips['uv_dest'].fillna("Outside Seattle")
df_trips['uvType_dest'] = df_trips['uvType_dest'].fillna("Outside Seattle")

# Drop missing variables, clean up column
df_trips['mode_1'] = df_trips['mode_1'].fillna(0)
df_trips['mode_1'] = df_trips['mode_1'].astype(str).replace(' ', '0')
df_trips['mode_1'] = df_trips['mode_1'].astype(str).astype(int)
df_trips['travelers_total'] = df_trips['travelers_total'].astype(str).replace(' ', '0')
df_trips['travelers_total'] = df_trips['travelers_total'].astype(str).astype(int)

# drop rows where the duration or distance is null or an empty space
df_trips = df_trips[df_trips['google_duration'].notnull()]
df_trips = df_trips[df_trips['trip_path_distance'].notnull()]
df_trips = df_trips[df_trips['google_duration'] != " "]
df_trips = df_trips[df_trips['trip_path_distance'] != " "]
df_trips['google_duration'] = df_trips['google_duration'].astype(float)
df_trips['trip_path_distance'] = df_trips['trip_path_distance'].astype(float)
df_trips = df_trips[df_trips['trip_path_distance'].notnull()]

# Create OD Pairs for urban villages and block groups
df_trips['uv_od_pair'] = df_trips['uv_origin'] + " to " + df_trips['uv_dest']
df_trips['bg_od_pair'] = df_trips['bg_origin'].astype(str) + " to " + df_trips['bg_dest'].astype(str)

# Assign mode variables
df_trips['mode'] = np.where(df_trips['mode_1']==1, "Walk", "Other")
df_trips['mode'] = np.where(df_trips['mode_1']==2, "Bike", df_trips['mode'])

df_trips['mode'] = np.where((df_trips['mode_1']>=3) & (df_trips['mode_1']<=17)  & (df_trips['travelers_total']==1), "Drive Alone", df_trips['mode'])
df_trips['mode'] = np.where(((df_trips['mode_1']==21) | (df_trips['mode_1']==22) |
                                 (df_trips['mode_1']==33) | (df_trips['mode_1']==34) | (df_trips['mode_1']==18))
                                 & (df_trips['travelers_total']==1), "Drive Alone", df_trips['mode'])

df_trips['mode'] = np.where((df_trips['mode_1']>=3) & (df_trips['mode_1']<=17)  & (df_trips['travelers_total']!=1), "Drive w Others", df_trips['mode'])
df_trips['mode'] = np.where(((df_trips['mode_1']==21) | (df_trips['mode_1']==22) |
                                 (df_trips['mode_1']==33) | (df_trips['mode_1']==34) | (df_trips['mode_1']==18))
                                 & (df_trips['travelers_total']>1), "Drive w Others", df_trips['mode'])

df_trips['mode'] = np.where((df_trips['mode_1']==23) | (df_trips['mode_1']==41) | (df_trips['travelers_total']==42), "Transit", df_trips['mode'])
df_trips['mode'] = np.where((df_trips['mode_1']==32) | (df_trips['travelers_total']==52), "Transit", df_trips['mode'])

df_trips['drive_alone'] = np.where(df_trips['mode']=="Drive Alone", 1, 0)


# Assign purpose variables
df_trips['purpose'] = np.where(df_trips['d_purp']==1, "Go Home", "Other")
df_trips['purpose'] = np.where(df_trips['d_purp']==6, "School", df_trips['purpose'])
df_trips['purpose'] = np.where((df_trips['d_purp']==10) | (df_trips['d_purp']==11), "Work", df_trips['purpose'])

# Assign time period variables
df_trips['depart_time_timestamp'] = pd.to_datetime(df_trips['depart_time_timestamp'], errors='coerce')
df_trips['depart_day'] = df_trips['depart_time_timestamp'].dt.dayofweek
df_trips['depart_time'] = df_trips['depart_time_timestamp'].dt.hour

df_trips['depart_period'] = np.where((df_trips['depart_day']>=0) & (df_trips['depart_day']<=4) & 
                                     (df_trips['depart_time']>=7) & (df_trips['depart_time']<=9), "Weekday AM", "")

df_trips['depart_period'] = np.where((df_trips['depart_day']>=0) & (df_trips['depart_day']<=4) & 
                                     (df_trips['depart_time']>=10) & (df_trips['depart_time']<=15), "Weekday Mid", df_trips['depart_period'])

df_trips['depart_period'] = np.where((df_trips['depart_day']>=0) & (df_trips['depart_day']<=4) & 
                                     (df_trips['depart_time']>=16) & (df_trips['depart_time']<=19), "Weekday PM", df_trips['depart_period'])

df_trips['depart_period'] = np.where((df_trips['depart_day']>=0) & (df_trips['depart_day']<=4) & 
                                     (df_trips['depart_time']<7), "Other", df_trips['depart_period'])

df_trips['depart_period'] = np.where((df_trips['depart_day']>=0) & (df_trips['depart_day']<=4) & 
                                     (df_trips['depart_time']>19), "Late Night", df_trips['depart_period'])

df_trips['depart_period'] = np.where((df_trips['depart_day']>=5) & (df_trips['depart_day']<=6), "Late Night", df_trips['depart_period'])

#dts = dfBad[cols].apply(lambda x: pd.to_datetime(x, errors='coerce', format='%m/%d/%Y'))
#pd.to_datetime(df_trips['depart_time_timestamp'])

#df_trips['depart_time_timestamp'] = datetime.strptime(df_trips['depart_time_timestamp'], '%b %d %Y %I:%M%p')
#to_datetime

#print (df_trips.dtypes)
print (df_trips.head())

/Users/xx/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/xx/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/xx/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

          tripid      hhid  origin_lat  origin_lng   dest_lat   dest_lng  \
2   1.710000e+12  17119958   47.707597 -122.118828  999.00000  999.00000
3   1.710000e+12  17119958   47.707597 -122.118828  999.00000  999.00000
4   1.710000e+12  17119958   47.707597 -122.118828  999.00000  999.00000
9   1.710000e+12  17108513   34.857550  132.033550   31.68794  124.34331
10  1.710000e+12  17108513   31.150120  121.798040   31.31629  120.66029

       bg_origin bg_dest    personid  google_duration      ...        \
2   530330323213    none  1711995801              4.0      ...
3   530330323213    none  1711995803              4.0      ...
4   530330323213    none  1711995804              4.0      ...
9           none    none  1710851301             54.0      ...
10          none    none  1710851301            118.0      ...

            uv_dest      uvType_dest                          uv_od_pair  \
2   Outside Seattle  Outside Seattle  Outside Seattle to Outside Seattle
3   Outside Seattle  Outside Seattle  Outside Seattle to Outside Seattle
4   Outside Seattle  Outside Seattle  Outside Seattle to Outside Seattle
9   Outside Seattle  Outside Seattle  Outside Seattle to Outside Seattle
10  Outside Seattle  Outside Seattle  Outside Seattle to Outside Seattle

              bg_od_pair            mode drive_alone  purpose  depart_day  \
2   530330323213 to none  Drive w Others           0    Other         3.0
3   530330323213 to none  Drive w Others           0    Other         3.0
4   530330323213 to none  Drive w Others           0    Other         3.0
9           none to none           Other           0    Other         0.0
10          none to none           Other           0    Other         0.0

   depart_time  depart_period
2          8.0     Weekday AM
3          8.0     Weekday AM
4          8.0     Weekday AM
9          1.0          Other
10         3.0          Other

[5 rows x 32 columns]

## Origin and Destination Summary

In [6]:
#filter for only trips starting and ending in Seattle
df_trips_Seattle = df_trips[(df_trips['uv_origin'] != 'Outside Seattle') | (df_trips['uv_dest'] != 'Outside Seattle')]

#print (df_trips_Seattle)

#aggregate by urban village origin
df_UV_Origins = df_trips_Seattle.groupby(['uv_origin'], as_index=False).agg({'google_duration':['mean','std','skew'],'trip_path_distance':['mean'],
                                                                            'origin_lat':['mean','std','skew'],'origin_lng':['mean']})

print (df_UV_Origins.head())

#aggregate by urban village destination
df_UV_Destinations = df_trips_Seattle.groupby(['uv_dest'], as_index=False).agg({'google_duration':['mean'],'trip_path_distance':['mean'],
                                                                                          'dest_lat':['mean'],'dest_lng':['mean']})
#print (df_UV_Destinations.head())

#aggregate by urban village OD Pair
df_UV_ODPair = df_trips_Seattle.groupby(['uv_od_pair'], as_index=False).agg({'google_duration':['mean'],'trip_path_distance':['mean'],
                                                                                          'origin_lat':['mean'],'origin_lat':['mean'],
                                                                                          'dest_lat':['mean'],'dest_lng':['mean']})
#print (df_UV_ODPair.head())

##aggregate by blockgroup origin
df_BG_Origins = df_trips_Seattle.groupby(['bg_origin'], as_index=False).agg({'google_duration':['mean'],'trip_path_distance':['mean'],
                                                                            'origin_lat':['mean'],'origin_lng':['mean']})
#print (df_BG_Origins)

#aggregate by blockgroup destination
df_BG_Destinations = df_trips_Seattle.groupby(['bg_dest'], as_index=False).agg({'google_duration':['mean'],'trip_path_distance':['mean'],
                                                                                          'dest_lat':['mean'],'dest_lng':['mean']})
#print (df_BG_Destinations.head())

#aggregate by urban village OD Pair
df_BG_ODPair = df_trips_Seattle.groupby(['bg_od_pair'], as_index=False).agg({'google_duration':['mean'],'trip_path_distance':['mean'],
                                                                            'origin_lat':['mean'],'origin_lng':['mean'],
                                                                             'dest_lat':['mean'],'dest_lng':['mean']})
df_BG_ODPair.columns = df_BG_ODPair.columns.droplevel(level=1)

df_BG_ODPair.to_csv(data_dir + 'df_BG_ODPair.csv', mode='w', header=True, index=False)
df_BG_Origins.to_csv(data_dir + 'BG_Origins.csv', mode='w', header=True, index=False)

               uv_origin google_duration                       \
                                    mean        std      skew
0            12th Avenue       16.684028  15.493985  3.433822
1   23rd & Union-Jackson       15.564369  14.651732  3.482621
2                Admiral       13.990654  11.758173  1.232974
3  Aurora-Licton Springs       16.343915  13.910217  2.610908
4                Ballard       14.523540  14.356801  4.427405

  trip_path_distance origin_lat                      origin_lng
                mean       mean       std      skew        mean
0           4.193542  47.608315  0.002951 -0.462030 -122.317345
1           3.263156  47.603145  0.005409  1.487280 -122.306682
2           3.490138  47.582350  0.000786  2.643821 -122.386420
3           4.471715  47.696854  0.005029  0.480625 -122.345977
4           3.437674  47.670593  0.003032  0.103379 -122.382603

## Merged, Normalized Trip Dataset

In [34]:
df_trip_household= pd.merge(left=df_trips, right=df_households, how='left', left_on='hhid', right_on='hhid')

print (df_trip_household.head())

df_trip_household.to_csv(data_dir + 'Trip_Household_Merged.csv', mode='w', header=True, index=False)
df_UV_Origins.to_csv(data_dir + 'UV_Origins.csv', mode='w', header=True, index=False)

         tripid      hhid  origin_lat  origin_lng   dest_lat   dest_lng  \
0  1.710000e+12  17119958   47.707597 -122.118828  999.00000  999.00000
1  1.710000e+12  17119958   47.707597 -122.118828  999.00000  999.00000
2  1.710000e+12  17119958   47.707597 -122.118828  999.00000  999.00000
3  1.710000e+12  17108513   34.857550  132.033550   31.68794  124.34331
4  1.710000e+12  17108513   31.150120  121.798040   31.31629  120.66029

      bg_origin bg_dest    personid  google_duration    ...      \
0  530330323213    none  1711995801              4.0    ...
1  530330323213    none  1711995803              4.0    ...
2  530330323213    none  1711995804              4.0    ...
3          none    none  1710851301             54.0    ...
4          none    none  1710851301            118.0    ...

                  tenure race_afam race_aiak  race_asian race_hapi race_white  \
0  Between 3 and 5 years       0.0       1.0         2.0       0.0        0.0
1  Between 3 and 5 years       0.0       1.0         2.0       0.0        0.0
2  Between 3 and 5 years       0.0       1.0         2.0       0.0        0.0
3  Between 2 and 3 years       0.0       0.0         0.0       0.0        2.0
4  Between 2 and 3 years       0.0       0.0         0.0       0.0        2.0

   race_other  race_hisp race_total  pct_white
0         0.0        0.0        2.0        0.0
1         0.0        0.0        2.0        0.0
2         0.0        0.0        2.0        0.0
3         0.0        0.0        2.0        1.0
4         0.0        0.0        2.0        1.0

[5 rows x 58 columns]